### ISSUE TITLE
Kindly Update the ReadMe 

### ISSUE THREAD

**Issue by tnayanam** [stephenmuecke/mvc-collectionvalidation#1]
Hello Sir, Kindly update the read me with an example so that I can understand what this utility is. Thanks!

**Comment by stephenmuecke** [comment]
@tnayanam, Apologies. I had meant to make this project private, at least for the next couple of weeks (it was just uploaded initially for another user to help out writing a few unit tests). But to briefly explain the project - asp.net-mvc uses the `jquery.validate.unobtrusive.js` and `jquery.validate.js plugins` for client side validation associated with `ValidationAttribute`'s applied to properties, however you cannot use that with properties that are collections of complex objects. This project aims to solve that. For example, given you have a `User` model where you want to assign `Roles` (using checkboxes in a view) and you want both client and server side validation to ensure that at least 2 roles are selected

**Comment by stephenmuecke** [comment]
@tnayanam. ReadMe file now updated

**Comment by tnayanam** [comment]
Thank You Sir. Appreciate it. :)
